# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idParlamentar', models.IntegerField(blank=True, default=0)),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('nomeParlamentar', models.CharField(blank=True, default='', max_length=100)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'masculino'), ('F', 'feminino')], default='', max_length=9)),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='', max_length=2)),
                ('partido', models.CharField(blank=True, default='', max_length=20)),
                ('condicao', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('urlFoto', models.URLField(blank=True, default='')),
                ('fone', models.CharField(blank=True, default='', max_length=9)),
                ('qtdPropostas', models.IntegerField(blank=True, default=0)),
                ('qtdPresencas', models.IntegerField(blank=True, default=0)),
                ('produtividade', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'deputado',
                'verbose_name_plural': 'deputados',
            },
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proposicao', models.IntegerField(blank=True, default=0)),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('numero', models.IntegerField(blank=True, default=0)),
                ('tipo', models.CharField(blank=True, choices=[('MPV', 'MPV'), ('MSC', 'MSC'), ('REQ', 'REQ'), ('PEC', 'PEC'), ('PRC', 'PRC'), ('PLP', 'PLP'), ('PL', 'PL'), ('PLN', 'PLN'), ('PDC', 'PDC'), ('REP', 'REP')], default='', max_length=3)),
                ('ano', models.IntegerField(blank=True, default=0)),
                ('ementa', models.TextField(blank=True, default='')),
                ('explicacao', models.TextField(blank=True, default='')),
                ('indexacao', models.TextField(blank=True, default='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Deputado')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'proposicao',
                'verbose_name_plural': 'proposicoes',
            },
        ),
    ]
