# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('', 'MPV'), ('', 'MSC'), ('', 'REQ'), ('', 'PEC'), ('', 'PRC'), ('', 'PLP'), ('', 'PL'), ('', 'PLN'), ('', 'PDC'), ('', 'REP')], default='', max_length=3)),
                ('ano', models.IntegerField(blank=True, default='')),
                ('numero', models.IntegerField(blank=True, default=0)),
                ('ementa', models.TextField()),
                ('explicacao', models.TextField()),
                ('autor', models.CharField(blank=True, default='', max_length=254)),
                ('indexacao', models.TextField()),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'proposicao',
            },
        ),
        migrations.AlterModelOptions(
            name='deputado',
            options={'ordering': ('nome',), 'verbose_name': 'deputado'},
        ),
        migrations.AddField(
            model_name='deputado',
            name='condicao',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deputado',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='deputado',
            name='fone',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='deputado',
            name='idParlamentar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='deputado',
            name='nomeParlamentar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deputado',
            name='partido',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deputado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'masculino'), ('F', 'feminino')], default='', max_length=9),
        ),
        migrations.AddField(
            model_name='deputado',
            name='uf',
            field=models.CharField(blank=True, choices=[('', 'AC'), ('', 'AL'), ('', 'AP'), ('', 'AM'), ('', 'BA'), ('', 'CE'), ('', 'DF'), ('', 'ES'), ('', 'GO'), ('', 'MA'), ('', 'MT'), ('', 'MS'), ('', 'MG'), ('', 'PA'), ('', 'PB'), ('', 'PR'), ('', 'PE'), ('', 'PI'), ('', 'RJ'), ('', 'RN'), ('', 'RS'), ('', 'RO'), ('', 'RR'), ('', 'SC'), ('', 'SP'), ('', 'SE'), ('', 'TO')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='deputado',
            name='urlFoto',
            field=models.URLField(blank=True, default=''),
        ),
    ]
