# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171026_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deputado',
            options={'ordering': ('nome',), 'verbose_name': 'deputado', 'verbose_name_plural': 'deputados'},
        ),
        migrations.AlterModelOptions(
            name='proposicao',
            options={'ordering': ('nome',), 'verbose_name': 'proposicao', 'verbose_name_plural': 'proposicoes'},
        ),
        migrations.AddField(
            model_name='deputado',
            name='produtividade',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='deputado',
            name='qtdPresencas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='deputado',
            name='qtdPropostas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='id_proposicao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='ano',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('MPV', 'MPV'), ('MSC', 'MSC'), ('REQ', 'REQ'), ('PEC', 'PEC'), ('PRC', 'PRC'), ('PLP', 'PLP'), ('PL', 'PL'), ('PLN', 'PLN'), ('PDC', 'PDC'), ('REP', 'REP')], default='', max_length=3),
        ),
    ]
