# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-27 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171027_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='ementa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='explicacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='indexacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
